[SPARK-49291] Fix `javadoc` generation and add `lint` test pipeline to prevent
### What changes were proposed in this pull request?

This PR aims to fix `javadoc` generation and add `lint` GitHub Action job to prevent.

In addition, `HelmChart` lint step is also moved into new `lint` GitHub Action job.

### Why are the changes needed?

Currently, `javadoc` task fails due to `bad HTML entity` errors.
```
$ ./gradlew javadoc
...
> Task :spark-operator:javadoc FAILED
/Users/dongjoon/APACHE/spark-kubernetes-operator/spark-operator/src/main/java/org/apache/spark/k8s/operator/config/SparkOperatorConfigMapReconciler.java:43: error: bad HTML entity
 * is located in given config map. It would keep watch the config map & apply changes when update is
...
4 errors
...
BUILD FAILED in 1s
8 actionable tasks: 1 executed, 7 up-to-date
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs with newly added `lint` CI test job.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #62 from dongjoon-hyun/SPARK-49291.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>