[SPARK-53639] Use `spark` consistently for `release-name` of Helm installation
### What changes were proposed in this pull request?

This PR aims to use `spark` consistently for `release-name` of Helm installation.

### Why are the changes needed?

Although we use `spark` in `README.md` and website like the following, old legacy names still exist.

https://github.com/apache/spark-kubernetes-operator/blob/cfd5063c595c445eee3d9d94e5dc9d17590ed5d4/README.md?plain=1#L49

We need to unify this. Otherwise, `INSTALLATION FAILED` occurs due to the mismatch of `meta.helm.sh/release-name`.

```
$ helm install sparkx --create-namespace -f build-tools/helm/spark-kubernetes-operator/values.yaml build-tools/helm/spark-kubernetes-operator/
Error: INSTALLATION FAILED: Unable to continue with install: ServiceAccount "spark-operator" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "sparkx": current value is "spark"
```

### Does this PR introduce _any_ user-facing change?

No for the clean installations.

For the users who have the existing installation, they need to remove old K8s objects before installation.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #323 from dongjoon-hyun/SPARK-53639.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>